# This playbook deploys WebCert 

- hosts: tomcat
  sudo: yes 
  vars:
    # repo - values: snapshot or release
    repo: release
    version: 3.1.0-b61
    config_version: master

  roles:
    - app-resources
    - webcert
