---
# This playbook deploys WebCert 

- hosts: tomcat
  sudo: yes 
  vars:
    # repo - values: snapshot or release
    repo: release

    version: 3.0.0
    config_version: origin/release/v3.0.0

  roles:
    - app-resources
    - webcert
